### ISSUE TITLE
RTL does not start on new RaspiBlitz v1.3 test build on Raspberry Pi 4 and Odroid HC1

### ISSUE THREAD

**Issue by openoms** [ShahanaFarooqui/RTL#173] opened 2019-08-02 23:26 UTC
**Describe the bug**
Installing NodeJS from binaries, than building RTL from source complains about some missing non-essential dependencies. RTL.service exits with error.

**To Reproduce**
Buidl cusrom SD card from Raspiblitz v1.3 branch.
Install RTL from terminal menu.

**Expected behavior**
RTL running as systemctl service

**Actual behavior**
RTL service stops with error.
```
* RTL.service - RTL daemon
   Loaded: loaded (/etc/systemd/system/RTL.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-08-02 23:01:34 UTC; 4s ago
  Process: 1866 ExecStart=/usr/bin/node /home/admin/RTL/rtl --lndir /home/admin/.lnd/data/chain/bitcoin/mainnet (code=exited, status=203/EXEC)
 Main PID: 1866 (code=exited, status=203/EXEC)
```

Log output of reinstalling RTL:
https://gist.github.com/openoms/bc0f2c5054cb7338ada47b6eab7f3b29

**Your environment**
* version of `lnd` 0.7.1
* operating system Linux odroidxu4 4.14.133-odroidxu4 #2 SMP PREEMPT Tue Jul 16 19:33:01 CEST 2019 armv7l GNU/Linux
* version of `bitcoind`: 0.18.0
* any other relevant environment details: Running behind Tor

RTL version was set to: `git reset --hard v0.4.3`

**Comment by openoms** [comment] 2019-08-03 06:54
during install when building the version 0.4.4 I get: 
```
OK - RTL code copy looks good

*** Run: npm install ***

> node-sass@4.12.0 install /home/admin/RTL/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-arm-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux-arm-64_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> core-js@3.1.4 postinstall /home/admin/RTL/node_modules/@angular-devkit/build-angular/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
```

Also the prompt for sending info to Google is present as mentioned here: 
https://github.com/ShahanaFarooqui/RTL/issues/172

**Comment by fluidvoice** [comment] 2019-08-04 18:49
Also fails to install for me on v1.3 (in a VM) - will delete this post if I find it's specific to the VM environment.  

```
node-v10.16.0-linux-x64/include/node/v8-profiler.h
node-v10.16.0-linux-x64/include/node/node_api.h
node-v10.16.0-linux-x64/include/node/node_version.h
node-v10.16.0-linux-x64/include/node/zlib.h
node-v10.16.0-linux-x64/include/node/zconf.h

*** Get the RTL Source Code ***
Cloning into 'RTL'...
remote: Enumerating objects: 367, done.
remote: Counting objects: 100% (367/367), done.
remote: Compressing objects: 100% (249/249), done.
remote: Total 3503 (delta 226), reused 202 (delta 111), pack-reused 3136
Receiving objects: 100% (3503/3503), 19.16 MiB | 520.00 KiB/s, done.
Resolving deltas: 100% (2431/2431), done.
HEAD is now at 4306675 Issue #160 default node setup
FAIL - code copy did not run correctly
ABORT - RTL install 
```

Full log:
https://gist.github.com/fluidvoice/ecda993c9b59d6a6df83668ff24d3b5f

**Comment by openoms** [comment] 2019-08-05 16:58
Came across the same issue unfortunately when building on my RPi4 based on Raspbian Buster with Desktop:
![Screenshot from 2019-08-05 17-51-19](https://user-images.githubusercontent.com/43343391/62481469-6ba7e780-b7aa-11e9-9c2b-7f8b36a87702.png)

**Comment by openoms** [comment] 2019-08-06 07:55
To problem seems to resolve when I`ve run:
`sudo apt install -y npm`
`sudo systemctl restart RTL`
Managed to start and use RTl version 0.3.1 and 0.4.4.
@fluidvoice can you confirm please?

**Comment by grnqrtr** [comment] 2019-08-07 14:05
I can confirm that this fixed RTL for me too. Though it looks like I'm running RTL 0.4.2-beta for some reason? I enabled/installed RTL through the menu. I'm using v1.3 RC2 on RPi4.

**Comment by ShahanaFarooqui** [comment] 2019-08-08 01:47
@openoms, @grnqrtr Thanks a lot for solving the issue and sharing the solution with us too. Appreciated, feeling like a team :). Can i close the issue or do we still need to check anything?

**Comment by fluidvoice** [comment] 2019-08-08 19:07
> To problem seems to resolve when I've run:
> `sudo apt install -y npm`
> `sudo systemctl restart RTL`
> Managed to start and use RTL version 0.3.1 and 0.4.4.
> @fluidvoice can you confirm please?

For me in my VM sadly no...

> Aug  8 15:01:54 debian systemd[1]: Started Bitcoin daemon.
> Aug  8 15:01:54 debian systemd[1]: Starting LND Lightning Daemon...
> Aug  8 15:01:54 debian systemd[1]: Started LND Lightning Daemon.
> Aug  8 15:01:54 debian systemd[1]: Started RTL daemon.
> Aug  8 15:01:54 debian systemd[1]: Reached target Multi-User System.
> Aug  8 15:01:54 debian systemd[1]: Reached target Graphical Interface.
> Aug  8 15:01:54 debian systemd[1]: Starting Update UTMP about System Runlevel Changes...
> Aug  8 15:01:54 debian systemd[1]: systemd-update-utmp-runlevel.service: Succeeded.
> Aug  8 15:01:54 debian systemd[1]: Started Update UTMP about System Runlevel Changes.
> Aug  8 15:01:54 debian systemd[1]: Startup finished in 4.241s (kernel) + 13.620s (userspace) = 17.862s.
> Aug  8 15:01:56 debian node[1151]: internal/modules/cjs/loader.js:583
> Aug  8 15:01:56 debian node[1151]:     throw err;
> Aug  8 15:01:56 debian node[1151]:     ^
> Aug  8 15:01:56 debian node[1151]: Error: Cannot find module 'express'
> Aug  8 15:01:56 debian node[1151]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
> Aug  8 15:01:56 debian node[1151]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
> Aug  8 15:01:56 debian node[1151]:     at Module.require (internal/modules/cjs/loader.js:637:17)
> Aug  8 15:01:56 debian node[1151]:     at require (internal/modules/cjs/helpers.js:22:18)
> Aug  8 15:01:56 debian node[1151]:     at Object.<anonymous> (/home/admin/RTL/app.js:2:17)
> Aug  8 15:01:56 debian node[1151]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
> Aug  8 15:01:56 debian node[1151]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> Aug  8 15:01:56 debian node[1151]:     at Module.load (internal/modules/cjs/loader.js:599:32)
> Aug  8 15:01:56 debian node[1151]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> Aug  8 15:01:56 debian node[1151]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> Aug  8 15:01:56 debian systemd[1]: RTL.service: Main process exited, code=exited, status=1/FAILURE
> Aug  8 15:01:56 debian systemd[1]: RTL.service: Failed with result 'exit-code'.
> Aug  8 15:01:57 debian systemd[1]: Stopping User Manager for UID 114...

**Comment by fluidvoice** [comment] 2019-08-08 19:22
OK got it to work. I had to install these things which were missing in my case (VM with Debian 10). Not sure why?...

admin@debian:~/Documents$ grep "npm install" rtl-debug.txt 
admin@debian:~$ npm install express
admin@debian:~$ npm install cookie-parser
admin@debian:~$ npm install optimist
admin@debian:~$ npm install upper-case
admin@debian:~$ npm install jsonwebtoken
admin@debian:~$ npm install request-promise
admin@debian:~$ npm install atob

**Closed** 2019-08-16 07:32 UTC
Labels: Troubleshooting
