### ISSUE TITLE
Step3 Initiate RTL Webserver Error

### ISSUE THREAD

**Issue by anonymoustrident** [ShahanaFarooqui/RTL#87] opened 2019-03-19 03:15 UTC
I am getting an error message when i try to initiate RTL webserver

```
C:\RTL\connect.js:162
                throw new Error(errMsg);
                ^
```

Directory is correct as follows but error also shows
```
Error:
Default Node Authentication can be set with LND Config Path only. Please set LND Config Path through environment/RTL.conf!
```

To reproduce , I followed the above steps all without errors.
LND: 0.5.2 and node 4.11 installed successfully
Thanks

**Comment by ShahanaFarooqui** [comment] 2019-03-19 09:45
@anonymoustrident 
Can you please share the path of your RTL.conf? It should be available in the root folder.

The config file's 'nodeAuthType' should either be set as 'CUSTOM' or 'DEFAULT'. In your case, it looks like you are setting it to 'DEFAULT', when the nodeAuthType is 'DEFAULT' then 'lndConfigPath' variable should be set with lnd.conf file path "including" 'lnd.conf' like below:

[Authentication]
macaroonPath=D:\Users\....\AppData\Local\...\data\...\bitcoin\testnet
nodeAuthType=DEFAULT
lndConfigPath=D:\Users\...\AppData\Local\Lnd\lnd.conf

**Comment by anonymoustrident** [comment] 2019-03-19 10:02
Thanks for your reply. 
Path is 
`C:\Users\XXXXX\AppData\Local\Lnd\data\chain\bitcoin\testnet`

Maybe i can share with you the full error code. Ps. I'm not savvy with commands.

```
Default Node Authentication can be set with LND Config Path only. Please set LND Config Path through environment/RTL.conf!
    at validateConfigFile (C:\RTL\connect.js:162:9)
    at Object.connect.configFileExists (C:\RTL\connect.js:257:5)
    at Object.<anonymous> (C:\RTL\connect.js:274:26)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\RTL\rtl.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

Hope it helps. 
Thanks

**Comment by saubyk** [comment] 2019-03-19 10:13
Hi @anonymoustrident 
You have two options to resolve this issue:

option 1: In RTL.conf, set ‘nodeAuthType=DEFAULT’ and set ‘lndConfigPath’ correctly so that RTL can located LND.conf, and ensure that it has ‘rpcpass’ set.

option 2: In RTL.conf, set ‘nodeAuthType=CUSTOM’ and set ‘rtlPass’, so that it need not look for LND.conf

Hope this helps.

**Comment by anonymoustrident** [comment] 2019-03-19 10:17
Thanks Saubyk for the reply. 

Just to clarify in Option 1, what do you mean by ensure it has rpcpass set? where to find this rpcpass and set it to?

In option 2,  when you mentioned  set rtlPass, i see rtlpass but what should i set it to ? 

Hope this don't fustrates anyone.
Thanks heaps.!

**Comment by saubyk** [comment] 2019-03-19 10:30
Option 2 is a simpler approach.

You can set it to whatever you like in RTL.conf.

You will use that to access RTL.

**Comment by ShahanaFarooqui** [comment] 2019-03-19 10:33
@anonymoustrident Please feel free to ask as many questions as you have :).

Just to clarify in Option 1, what do you mean by ensure it has rpcpass set? 
[RTL]: As we can see, your RTL.conf file has empty values for "lndConfigPath=", so you need to define the full path value for this variable. Explore through your file system and find the path where your lnd.conf file is saved and set that path value for this variable. For example: if your lnd.conf file resides in 'C:\abc\xyz' folder then the value of lndConfigPath will be:
lndConfigPath=C:\abc\xyz\lnd.conf

where to find this rpcpass and set it to?
[RTL]: Open your lnd.conf file and ensure that the file has a variable like below:
[Bitcoind]
bitcoind.rpcpass=some_password_value

In option 2, when you mentioned set rtlPass, i see rtlpass but what should i set it to ?
[RTL]: If your lnd.conf file does not have rpcpass value, then RTL will not be able to authenticate your through 'DEFAULT' value. In that case, you need to set 'nodeAuthType=CUSTOM' and 'rtlPass=whatever_password_you_want_to_set' in your rtl.conf file. Then, you can use the rtlPass value as your RTL password.

Hope this helps.

**Comment by anonymoustrident** [comment] 2019-03-20 05:52
Thank You very much to both @saubyk and @ShahanaFarooqui for your patience and explanation. After reading both option 1 and option 2 , I understand what it means about the rtlpass and the config path missing that result in it not being able to the rtlpass. So if I change it to custom, it will not search for the path and instead you need to type the rtlpass equivalent on the console in localhost:3000 instead . If it is set to default and the path can be found, then it will take the key from the value rtlpass instead. Correct me if my understanding is inaccurate .

Again, im grateful for the quick and efficient reply .

**Comment by anonymoustrident** [comment] 2019-03-20 05:56
Oh , new issue faced on the console. It is not unlocked and when i type in my password, Error message : LND config reading message failed. errno:-4068 , error code: EISDIR , syscall: read

Password is correct.

**Comment by ShahanaFarooqui** [comment] 2019-03-20 12:58
@anonymoustrident 
1) Slight correction is required for your RTL authentication process: There are two ways to get authenticated by RTL:
1.1) DEFAULT,
1.2) CUSTOM

1.1) if nodeAuthType is set to DEFAULT, then 
=> RTL reads lndConfigPath from 'RTL'conf' file.
=> Reads lnd.conf file from above path, searches for 'bitcoind.rpcpass' variable value.
=> Once the RTL server is up, user needs to open the browser and go to url 'http://localhost:3000'.
=> User will be asked to enter the RPC password in the browser.
=> User needs to enter the same value as 'bitcoind.rpcpass' value to get auhenticated.

1.2) if nodeAuthType is set to CUSTOM, then 
=> RTL reads the password value from 'RTL'conf' file itself. 
=> User needs to set the password within RTL.conf's variable 'rtlPass'.
=> Start RTL node server, open 'http://localhost:3000' in the browser.
=> User can enter the password value same as assigned to 'rtlPass' to get authenticated.

2) You do not need to define lndir path in the node console anymore. I believe that the whole confusion is due to wrong readme link. That command was required initially but as RTL evolved, the setup process evolved and became more intuitive. Please DO NOT follow the old link and check our new link to follow new setup process. (Updated the old read me file also, to avoid further confusion.)
[https://github.com/ShahanaFarooqui/RTL]

**Comment by anonymoustrident** [comment] 2019-03-21 09:34
Thanks for pointing that out @ShahanaFarooqui . I tried to proceed with CUSTOM and taken a look at the URL you provided above but I am still getting the same error from the console. No change at all.

Any idea how can I rectify or what code you need to see, I can get it for you.

**Comment by ShahanaFarooqui** [comment] 2019-03-21 09:39
@anonymoustrident can you please share your RTL.conf from the root directory? Please mask your password before sharing.

**Comment by anonymoustrident** [comment] 2019-03-21 09:42
Here you go , I can't find the cookie anywhere in my RTL root but I just took it from yours
```
[Authentication]
macaroonPath=C:\Users\USER\AppData\Local\Lnd\data\chain\bitcoin\testnet
nodeAuthType=CUSTOM
lndConfigPath=C:\Users\USER\AppData\Local\Lnd
rtlPass=***

[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
bitcoindConfigPath=
enableLogging=true
port=3000
lndServerUrl=https://localhost:8080/v1

[SSO]
rtlSSO=0
rtlCookiePath=C:\RTL\cookies\auth.cookie
logoutRedirectLink=/login
```

**Comment by anonymoustrident** [comment] 2019-03-22 02:02
1. Yes , confirm that there is a .conf at the end. 
2. Yes, please take a look at the commands. 
```
C:\Users\USER\RTL>node rtl
C:\Users\USER\RTL\connect.js:162
                throw new Error(errMsg);
                ^

Error: Please set macaroon path through environment or RTL.conf!
Default Node Authentication can be set with LND Config Path only. Please set LND Config Path through environment or RTL.conf!
    at validateConfigFile (C:\Users\USER\RTL\connect.js:162:9)
    at Object.connect.configFileExists (C:\Users\USER\RTL\connect.js:257:5)
    at Object.<anonymous> (C:\Users\USER\RTL\connect.js:274:26)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\USER\RTL\rtl.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
3.  I can't seem to find this path . Macaroonpath nor can i see any admin.macaroon 

> Finally, if the nodeAuthType is set as CUSTOM then RTL doesn't even execute that code. So this error can only occur if nodeAuthType is not CUSTOM. So please ensure that it is reading this conf file.  Yes, it is , I have saved it once more just to be sure.

**Comment by ShahanaFarooqui** [comment] 2019-03-22 02:12
@anonymoustrident 
That is the problem. LND REST APIs can not be called without passing admin.macaroon. You can consider this file as a password for LND API calls. 

In one of the above messages, you confirmed that you are setting macaroonPath in RTL.conf as:
macaroonPath=C:\Users\USER\AppData\Local\Lnd\data\chain\bitcoin\testnet

So, we assumed that this path has your 'admin.macaroon' file. Please find your admin.macaroon path and define that in RTL.conf to solve your issue.

**Comment by anonymoustrident** [comment] 2019-03-22 03:03
@ShahanaFarooqui , as sick as it sounds. its gratifying to be able to make sense and solve it. I guess what confuses me was the lnd.conf , rtf.conf and the macaroon was found within the chain data . I was looking for it at the root of LND or RTL. 

I am now able to log in to the console. Thank you @ShahanaFarooqui . However, there arise a new issue. 

When i do node rtl, i receive the same error on Macaroon , the fact is , macaroon has already been attached. 

But when i use --lndir after node rtl, it shows `Server is up and running, please open the UI at http://localhost:3000`

**Comment by ShahanaFarooqui** [comment] 2019-03-22 03:15
@anonymoustrident somehow RTL is still unable to find your RTL.conf file and that is why it is throwing error with ‘node rtl’ command. 

Please follow below steps in order:
1: Go to your root directory in the command prompt,
2: Execute command “SET RTL_CONFIG_PATH=your-rtl-root-path\RTL.conf”
3: Run “node rtl” only. Setting —lndir will only set your macaroonPath but you need other configurations also for the long run.

**Comment by ShahanaFarooqui** [comment] 2019-03-22 03:18
@anonymoustrident
Just out of curiosity, did you open ‘http://localhost:3000’ in the browser after getting the success message in command? We’re you able to authenticate there?

**Comment by anonymoustrident** [comment] 2019-03-22 06:01
> @anonymoustrident somehow RTL is still unable to find your RTL.conf file and that is why it is throwing error with ‘node rtl’ command.
> 
> Please follow below steps in order:
> 1: Go to your root directory in the command prompt,
> 2: Execute command “SET RTL_CONFIG_PATH=your-rtl-root-path\RTL.conf”
> 3: Run “node rtl” only. Setting —lndir will only set your macaroonPath but you need other configurations also for the long run.

@ShahanaFarooqui , The macaroon error is solved now. Back to this.  
```
C:\Users\USER\RTL>node rtl
C:\Users\USER\RTL\connect.js:162
                throw new Error(errMsg);
                ^

Error:
Default Node Authentication can be set with LND Config Path only. Please set LND Config Path through environment or RTL.conf!
    at validateConfigFile (C:\Users\USER\RTL\connect.js:162:9)
    at Object.connect.configFileExists (C:\Users\USER\RTL\connect.js:257:5)
    at Object.<anonymous> (C:\Users\USER\RTL\connect.js:274:26)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\USER\RTL\rtl.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
I realized there are a few rtl.conf file. 1 is found in the root of rtl.conf and one is within the chain itself. 
The funny thing is , I am able to log into the console now.

**Comment by saubyk** [comment] 2019-03-22 11:01
@anonymoustrident 

Please delete any RTL.conf files, other then the one in the RTL folder.
And share the content of your RTL.conf and lnd.conf (mask the sensitive information).

**Comment by saubyk** [comment] 2019-03-23 16:52
@anonymoustrident 
Please let us know, if you are able to make progress. Thanks.

**Comment by anonymoustrident** [comment] 2019-03-24 04:24
> @anonymoustrident
> 
> Please delete any RTL.conf files, other then the one in the RTL folder.
> And share the content of your RTL.conf and lnd.conf (mask the sensitive information).

OKay. 

```
# Auto-Generated Configuration File

# Node Launcher version 5.3.0

debuglevel=debug
restlisten=127.0.0.1:8080
listen=127.0.0.1:9735
rpclisten=localhost:10009

[Application Options]
alias=XXXLND
color=#68F450
debuglevel=debug
externalip=XX.XXX.XX.XXX
[Bitcoin]
# enable either testnet or mainnet
bitcoin.active=1
bitcoin.testnet=1
bitcoin.node=bitcoind
[Bitcoind]
bitcoind.rpcuser=	
bitcoind.rpcpass=
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
```

```
Server is up and running, please open the UI at http://localhost:**3005**
Console:
Conf: 7: 1553401111183: INFO: Getting RTL Config
Console:
Calling getinfo from lnd server url: INFO: https://localhost:8080/v1/getinfo
Console:
GetInfo: 9: 1553401114233: INFO: {"identity_pubkey":"XXXXXXXXXXXXXXXXXXXX2d23e3f545793f8d87f2a8277271a8d1d6e8be53c02901","alias":"0346e45b3cXXXXXXXXXX","num_peers":1,"block_height":1485768,"block_hash":"000000000004da376487cd9f6306576b1b9da687cde88d1aa8c418df87dd4984","synced_to_chain":true,"testnet":true,"chains":["bitcoin"],"best_header_timestamp":"1553400556","version":"0.5.2-beta commit=v0.5.2-beta"}
Console:
Balance: 9: 1553401114306: INFO: Request params: {"source":"channels"}Request Query: {} Balance Received: {}
Console:
Fees: 8: 1553401114318: INFO: Fee Received: {}
Console:
Peers: 11: 1553401114327: INFO: Alias: "Kava-test-3"
Console:
Channels: 43: 1553401114329: INFO: Channels with Alias: {}
Console:
Peers: 29: 1553401114330: INFO: Peers with Alias: {"peers":[{"pub_key":"XXXXXXXXXX1691f4ca522b02bbf2b6bf3df51237c6641038b9d04dca3e184303ad","address":"54.165.221.164:9765","bytes_sent":"1880012","bytes_recv":"7871548","ping_time":"237949","alias":"Kava-test-3"}]}
Console:
Channels: 55: 1553401114338: INFO: Pending/Closed Channels: {"total_limbo_balance":0,"btc_total_limbo_balance":0}
Console:
Invoice: 30: 1553401114355: INFO: Invoices List Received: {}
Console:
Invoice: 45: 1553401114356: INFO: Invoices List Received: {}
Console:
Payments: 10: 1553401114368: INFO: Payment Decoded Received: {}
Console:
Balance: 9: 1553401114380: INFO: Request params: {"source":"blockchain"}Request Query: {} Balance Received: {}
Console:
Graph: 33: 1553401114512: INFO: Network Info Received: {"avg_out_degree":3.1001070663811565,"max_out_degree":1033,"num_nodes":1868,"num_channels":5791,"total_network_capacity":"44791436005","avg_channel_size":7734663.444137455,"min_channel_size":"4000","max_channel_size":"16777216"}
Console:
Graph: 44: 1553401114514: INFO: Network Information After Rounding and Conversion: {"avg_out_degree":3.1001070663811565,"max_out_degree":1033,"num_nodes":1868,"num_channels":5791,"total_network_capacity":"44791436005","avg_channel_size":7734663.444137455,"min_channel_size":"4000","max_channel_size":"16777216"}
```
After cleaning up all the other RTL.conf files, I am able to make some sense out of the settings and i did SET path for macaroon and as there may be some temp files of the previous RTL in history, they said port 3000 is already used so i changed it to 3005 , guess this is also possible and it works. I enter the console and put in my password and got the above from the `node rtl` command. 

Do help me glance through it , if it is all good, i will proceed and we can close this issue.

**Comment by ShahanaFarooqui** [comment] 2019-03-24 04:37
@anonymoustrident Yes, it is possible to change the port through RTL.conf variable setting. And if you change the port to 3500 then just open any browser and type ‘localhost:3500’ and hit enter. But, I am not sure what do you mean by ‘opening the console and entering the password’? Rtl will ask for the password when you will open it in the browser. Second, how are you getting server up message with ** prefixed and suffixed with your port number?

**Comment by anonymoustrident** [comment] 2019-03-24 04:42
> @anonymoustrident Yes, it is possible to change the port through RTL.conf variable setting. And if you change the port to 3500 then just open any browser and type ‘localhost:3500’ and hit enter. But, I am not sure what do you mean by ‘opening the console and entering the password’? Rtl will ask for the password when you will open it in the browser. Second, how are you getting server up message with ** prefixed and suffixed with your port number?

@ShahanaFarooqui , yes , i enter password through the normal way from the console. 

> Second, how are you getting server up message with ** prefixed and suffixed with your port number?
Sorry, I don't understand the above.

**Comment by anonymoustrident** [comment] 2019-03-24 04:44
Latest RTL.conf file. 
```
[Authentication]
macaroonPath=C:\RTL\RTL.conf
nodeAuthType=CUSTOM
lndConfigPath=C:\Users\USER\AppData\Local\Lnd.conf
rtlPass=******

[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
lndServerUrl=https://localhost:8080/v1
bitcoindConfigPath=
enableLogging=false
port=3005

[SSO]
rtlSSO=0
rtlCookiePath=
logoutRedirectLink=/login
```

**Comment by ShahanaFarooqui** [comment] 2019-03-24 04:48
@anonymoustrident your conf looks perfect and you are already getting all the data from APIs. So, just open RTL at ‘localhost:3005’ in the browser, login and enjoy :).

**Comment by anonymoustrident** [comment] 2019-03-24 04:51
@ShahanaFarooqui , I closed everything and tried node rtl again. The same thing happen . It can't find the RTL.conf path. 

So how i go around is to again do `SET RTL_CONFIG_PATH=your-rtl-root-path\RTL.conf` and `node rtl` and open RTL at `localhost:3005` before everything works again. 

Question: Is this normal ? everything i need to guide it using SET RTL_CONFIG_PATH?

**Comment by ShahanaFarooqui** [comment] 2019-03-24 05:01
Assuming that you have RTL folder at C:/RTL, there are 2 big problems with your setup:
1) your RTL.conf file should be saved in ‘C:/RTL’. We confirmed before also that whether your RTL.conf is in the root or not? Please save it in C:/RTL folder, if you do not want to set its path every time you restart.

2) your macaroonPath can not be C:/RTL/RTL.conf. It should be a path where your LND’s ‘admin.macaroon’ file exists.

**Comment by anonymoustrident** [comment] 2019-03-24 07:33
> Assuming that you have RTL folder at C:/RTL, there are 2 big problems with your setup:
> 
> 1. your RTL.conf file should be saved in ‘C:/RTL’. We confirmed before also that whether your RTL.conf is in the root or not? Please save it in C:/RTL folder, if you do not want to set its path every time you restart.
> 2. your macaroonPath can not be C:/RTL/RTL.conf. It should be a path where your LND’s ‘admin.macaroon’ file exists.

1. I can confirm that the RTL.conf file is in the RTL folder , unless you are saying to create a folder call RTL.conf and put the conf file inside it?

2. Yea, so the macaroonPath should be `macaroonPath=C:\Users\USER\AppData\Local\Lnd\data\chain\bitcoin\testnet`

**Comment by ShahanaFarooqui** [comment] 2019-03-24 12:56
@anonymoustrident please check the macaroonPath value in RTL.conf which you shared here 5 messages before.

**Comment by saubyk** [comment] 2019-03-24 16:27
> > Assuming that you have RTL folder at C:/RTL, there are 2 big problems with your setup:
> > 
> > 1. your RTL.conf file should be saved in ‘C:/RTL’. We confirmed before also that whether your RTL.conf is in the root or not? Please save it in C:/RTL folder, if you do not want to set its path every time you restart.
> > 2. your macaroonPath can not be C:/RTL/RTL.conf. It should be a path where your LND’s ‘admin.macaroon’ file exists.
> 
> 1. I can confirm that the RTL.conf file is in the RTL folder , unless you are saying to create a folder call RTL.conf and put the conf file inside it?
> 2. Yea, so the macaroonPath should be `macaroonPath=C:\Users\USER\AppData\Local\Lnd\data\chain\bitcoin\testnet`

@anonymoustrident No need to create a folder called 'RTL.conf', just ensure that RTL.conf file is present in the 'C:/RTL' folder.

And please correct the path for 'macaroonPath'. It must not be 'RTL.conf'. Its has to be the path you shared in your last comment. This change should address your issue.

Thanks

**Comment by anonymoustrident** [comment] 2019-03-25 10:05
> @anonymoustrident please check the macaroonPath value in RTL.conf which you shared here 5 messages before.

Yup. Here is the latest which is also working. 
```
macaroonPath=C:\Users\USER\AppData\Local\Lnd\data\chain\bitcoin\testnet
nodeAuthType=CUSTOM
lndConfigPath=C:\Users\USER\AppData\Local\Lnd.conf
rtlPass=******

[SSO]
rtlSSO=0
rtlCookiePath=
logoutRedirectLink=/login
[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
lndServerUrl=https://localhost:8080/v1
bitcoindConfigPath=
enableLogging=false
port=3005
```

**Comment by saubyk** [comment] 2019-03-25 10:08
@anonymoustrident 
Looks like you have a working setup now. Closing this issue.

Thanks.

**Closed by saubyk** 2019-03-25 10:08 UTC
Labels: Troubleshooting

**Comment by anonymoustrident** [comment] 2019-03-26 09:02
Thank you for all the help @saubyk & @ShahanaFarooqui
