### ISSUE TITLE
multiple logins

### ISSUE THREAD

**Issue by thephizzz** [ShahanaFarooqui/RTL#190] opened 2019-10-12 20:54 UTC
I am required to enter the login password three times. Failing the first two times. This happens on every login.

**To Reproduce**
login & enter password

**Expected behavior**
one password entry

**Actual behavior**
two failed attempts, then entry

**Screenshots**

**Your environment**
* version of `lnd` - 0.7.1-beta
* operating system - raspiblitz
* version of `btcd - v0.18.1
* any other relevant environment details

**Additional context**

**Comment by ShahanaFarooqui** [comment] 2019-10-12 20:59
@thephizzz 

We need more information to be able to troubleshoot this issue. For example: 
What is your RTL version?
What is your RTL configuration?
Are you running it through any service? 
What are the error messages for first 2 try? RTL log/service log? 
Any relevant screenshots etc.

**Comment by thephizzz** [comment] 2019-10-12 21:20
RTL version 0.4-2 beta
Running on W10 system
Not through any service. On same home network as Raspiblitz
Screen shot of error.
![RTLError1](https://user-images.githubusercontent.com/56489745/66707779-7cc62500-ed14-11e9-9d28-fa3e30c66c07.png)

**Comment by thephizzz** [comment] 2019-10-12 21:21
Using Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by saubyk** [comment] 2019-10-12 21:23
Hi @thephizzz is the RTL server running on Raspiblitz or your Windows machine?

**Comment by thephizzz** [comment] 2019-10-12 21:24
Looking closer - it may be a time issue. Logging in one after the other times gives the error 2-3 times before entry.
But trying once and getting error. If I wait a minute before trying again - it allows access.

**Comment by thephizzz** [comment] 2019-10-12 21:25
@saubyk - not sure on that. I am running thr RTL from Chrome on the W10 server.

**Comment by saubyk** [comment] 2019-10-12 21:27
@thephizzz  can you please login to raspiblitz and run the below command:
`sudo journalctl -f -u RTL`

And then try to reproduce the login error.

We need to see the server log, when the login to RTL fails.

**Comment by thephizzz** [comment] 2019-10-12 21:28
Definitely time-based.
Logging in with error and letting page sit for a minute without clearing password allows entry

**Comment by thephizzz** [comment] 2019-10-12 21:29
Ok will do.

**Comment by thephizzz** [comment] 2019-10-12 21:31
admin@lndnode:~ $ sudo journalctl -f -u RTL
-- Logs begin at Sat 2019-10-12 02:31:14 BST. --
Oct 12 22:26:48 lndnode node[22318]: Error [ERR_CRYPTO_HASH_FINALIZED]: Digest already called
Oct 12 22:26:48 lndnode node[22318]:     at Hash.update (internal/crypto/hash.js:55:11)
Oct 12 22:26:48 lndnode node[22318]:     at /home/admin/RTL/controllers/authenticate.js:99:28
Oct 12 22:26:48 lndnode node[22318]:     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Oct 12 22:26:48 lndnode systemd[1]: RTL.service: Main process exited, code=exited, status=1/FAILURE
Oct 12 22:26:48 lndnode systemd[1]: RTL.service: Failed with result 'exit-code'.
Oct 12 22:27:19 lndnode systemd[1]: RTL.service: Service RestartSec=30s expired, scheduling restart.
Oct 12 22:27:19 lndnode systemd[1]: RTL.service: Scheduled restart job, restart counter is at 8.
Oct 12 22:27:19 lndnode systemd[1]: Stopped RTL daemon.
Oct 12 22:27:19 lndnode systemd[1]: Started RTL daemon.
Oct 12 22:29:30 lndnode node[29142]: internal/crypto/hash.js:55
Oct 12 22:29:30 lndnode node[29142]:     throw new ERR_CRYPTO_HASH_FINALIZED();
Oct 12 22:29:30 lndnode node[29142]:     ^
Oct 12 22:29:30 lndnode node[29142]: Error [ERR_CRYPTO_HASH_FINALIZED]: Digest already called
Oct 12 22:29:30 lndnode node[29142]:     at Hash.update (internal/crypto/hash.js:55:11)
Oct 12 22:29:30 lndnode node[29142]:     at /home/admin/RTL/controllers/authenticate.js:99:28
Oct 12 22:29:30 lndnode node[29142]:     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Oct 12 22:29:30 lndnode systemd[1]: RTL.service: Main process exited, code=exited, status=1/FAILURE
Oct 12 22:29:30 lndnode systemd[1]: RTL.service: Failed with result 'exit-code'.
Oct 12 22:30:00 lndnode systemd[1]: RTL.service: Service RestartSec=30s expired, scheduling restart.
Oct 12 22:30:00 lndnode systemd[1]: RTL.service: Scheduled restart job, restart counter is at 9.
Oct 12 22:30:00 lndnode systemd[1]: Stopped RTL daemon.
Oct 12 22:30:00 lndnode systemd[1]: Started RTL daemon.

**Comment by saubyk** [comment] 2019-10-12 21:37
@thephizzz are you running on Lightning on Litecoin?

Can you please share your `lnd.conf`.
*Do not forget to mask the sensitive info in the file, before sharing*

**Comment by thephizzz** [comment] 2019-10-12 21:43
No Litecoin. bitcoind.

![RTLError1](https://user-images.githubusercontent.com/56489745/66707997-b3516f00-ed17-11e9-9c52-151d4f2afd4e.png)

Screne shot of lnd.conf:

**Comment by saubyk** [comment] 2019-10-12 22:36
@thephizzz 
There was a bug in the authentication logic. We have fixed the issue and tagged a new release v0.5.3
https://github.com/ShahanaFarooqui/RTL/releases/tag/v0.5.3

You can download the latest release to get the issue addressed.

**Comment by thephizzz** [comment] 2019-10-12 22:54
Thank you. Very fast work. Impressed.

**Comment by thephizzz** [comment] 2019-10-12 23:09
Thanks for the update. How do I go about updating the current version?

I’m pretty new to Linux.

**Comment by saubyk** [comment] 2019-10-12 23:16
@thephizzz  follow the below steps:
1. Login to RaspiBlitz and go to the command line.
2. `cd RTL` <ensure that you are in the RTL directory>
3. ` sudo git pull`
4. `sudo npm install`
5. `sudo systemctl restart RTL`

**Comment by saubyk** [comment] 2019-10-14 01:05
@thephizzz assuming the issue is addressed now. Closing this issue.
Feel free to re-open if you face the same issue again. Thanks.

**Closed by saubyk** 2019-10-14 01:05 UTC
Labels: Troubleshooting
