### ISSUE TITLE
Broken menu

### ISSUE THREAD

**Issue by antonio-fr** [ShahanaFarooqui/RTL#175] opened 2019-08-08 12:44 UTC
[updated]
**Describe the bug**
Menu issue in latest RTL version 0.4.5 and 0.4.4. The menu menu is not operating.

**To Reproduce**
When clicking the menu icon : 
FF:
```
TypeError: this.sideNavigation is undefined
Stack trace:
sideNavToggle@https://blkhub.net/rtl/main-es2015.8bb100375aa6edf729e6.js:1:165819
X1/<@https://blkhub.net/rtl/main-es2015.8bb100375aa6edf729e6.js:1:1983270
handleEvent@https://blkhub.net/rtl/main-es2015.8bb100375aa6edf729e6.js:1:135951
handleEvent@https://blkhub.net/rtl/main-es2015.8bb100375aa6edf729e6.js:1:156480
cl@https://blkhub.net/rtl/main-es2015.8bb100375aa6edf729e6.js:1:89985
er/<@https://blkhub.net/rtl/main-es2015.8bb100375aa6edf729e6.js:1:129335
Kp/<@https://blkhub.net/rtl/main-es2015.8bb100375aa6edf729e6.js:1:283894
invokeTask@https://blkhub.net/rtl/polyfills-es2015.1db33451f25dd6f197fa.js:1:55451
onInvokeTask@https://blkhub.net/rtl/main-es2015.8bb100375aa6edf729e6.js:1:114134
invokeTask@https://blkhub.net/rtl/polyfills-es2015.1db33451f25dd6f197fa.js:1:55364
runTask@https://blkhub.net/rtl/polyfills-es2015.1db33451f25dd6f197fa.js:1:50936
invokeTask@https://blkhub.net/rtl/polyfills-es2015.1db33451f25dd6f197fa.js:1:56456
m@https://blkhub.net/rtl/polyfills-es2015.1db33451f25dd6f197fa.js:1:68432
b@https://blkhub.net/rtl/polyfills-es2015.1db33451f25dd6f197fa.js:1:68676
```

Chrome : 
```
main-es2015.8bb100375aa6edf729e6.js:1 ERROR TypeError: Cannot read property 'toggle' of undefined  
    at Ju.sideNavToggle (main-es2015.8bb100375aa6edf729e6.js:1)
    at Object.handleEvent (main-es2015.8bb100375aa6edf729e6.js:1)
    at Object.handleEvent (main-es2015.8bb100375aa6edf729e6.js:1)
    at Object.handleEvent (main-es2015.8bb100375aa6edf729e6.js:1)
    at cl (main-es2015.8bb100375aa6edf729e6.js:1)
    at l (main-es2015.8bb100375aa6edf729e6.js:1)
    at HTMLButtonElement.Kp.e (main-es2015.8bb100375aa6edf729e6.js:1)
    at a.invokeTask (polyfills-es2015.1db33451f25dd6f197fa.js:1)
    at Object.onInvokeTask (main-es2015.8bb100375aa6edf729e6.js:1)
    at a.invokeTask (polyfills-es2015.1db33451f25dd6f197fa.js:1)
```

It is like settingSidenav is not recognized here https://github.com/ShahanaFarooqui/RTL/blob/e89ca32109250c79e089f808e4cab5afd3abadf8/src/app/app.component.ts#L132

**Your environment**
* version of `lnd`
0.7.1-beta commit=v0.7.0-beta-188
* operating system (`uname -a` on *Nix)
Ubuntu 18.04 LTS
* version of `btcd`, `bitcoind`, or other backend
bitcoind 0.18.0
* any other relevant environment details
npm 3.5.2
node 8.10.0

**Additional context**
Tested on many differents web browsers

**Comment by ShahanaFarooqui** [comment] 2019-08-08 12:49
@antonio-fr 0.4.5 is not a stable version and in testing phase only. Please use latest stable version only (0.4.4-beta) as advised in readme.
Please let us know if issue exists in stable version too.

**Comment by antonio-fr** [comment] 2019-08-08 13:02
I have now tested the previous version : 0.4.4 is affected. Not the 0.4.3, menu icon is working well.

**Comment by antonio-fr** [comment] 2019-08-08 13:03
Angular 8 (used since https://github.com/ShahanaFarooqui/RTL/commit/a9e8ca6a758bc092b9a16f7363e9887a6351915c) wants node 10.9.0 and npm 6.2.0, I'm checking this.

**Comment by antonio-fr** [comment] 2019-08-08 13:22
I tested on a server with node 10.14.0 and npm 6.10.3, I can confirm the behavior is the exact same.
When clicking on the menu icon : *this.sideNavigation* is undefined for the toogle property

v0.4.3 : 🆗 
v0.4.4 : 🐛 
v0.4.5 : 🐛

**Comment by ShahanaFarooqui** [comment] 2019-08-08 13:32
@antonio-fr thanks a lot for the in depth testing and pictorial results :). We will check the issue and try to fix it by this weekend.

**Comment by ShahanaFarooqui** [comment] 2019-08-09 23:00
@antonio-fr, we are unable to reproduce the issue at our end. Can you please confirm if you ran 'npm install' after pulling the code? We upgraded angular from 7 to 8 with v0.4.4 and the initialization syntax is changed with the newer version. Not upgrading the dependencies can cause this issue. 

Pull the latest package.json from github,
Delete your local package-lock.json,
Delete node_modules folder from RTL,
Execute 'npm install'.

Please let us know if issue still persists.

**Comment by snowzach** [comment] 2019-08-14 18:42
I was using the docker version and have all sorts of strange issues with the menu and not being able to bring up peers. I rolled back to 0.4.3 and it's working fine.

**Comment by TechMiX** [comment] 2019-08-15 19:03
Experiencing this on 0.4.4
It is definitely something related to the pinning option for the side menu.
Any workarounds?

**Comment by ShahanaFarooqui** [comment] 2019-08-16 06:55
@antonio-fr , @snowzach , @TechMiX , thanks for raising and adding details to the issue. We finally were able to reproduce and fix the issue. Please get RTL v0.4.6 and try again.

**Comment by TechMiX** [comment] 2019-08-16 07:20
Thanks @ShahanaFarooqui, I pulled the latest changes and it is fixed now :)

**Comment by ShahanaFarooqui** [comment] 2019-08-21 01:49
Closing the issue as @TechMiX confirmed the fix.

**Closed by ShahanaFarooqui** 2019-08-21 01:49 UTC
Labels: Troubleshooting
